version:             '3'

services:

    api.chat:
        image: node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=api.chat.local
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./api_chat:/app/api_chat
        working_dir: /app/api_chat
        command: bash -c "npm i && npm start"

    # app.chat:
    #     image: node
    #     environment:
    #         - NODE_ENV=dev
    #         - VHOST_HOSTNAME=api.chat.local
    #     ports:
    #         - "80:8080"
    #     volumes:
    #         - ./app_chat:/app/app_chat
    #     working_dir: /app/app_chat
    #     command: bash -c "npm i && npm run serve"
    #     links:
    #         - api.chat
