version:             '3'

services:

    websocket.chat:
        image: node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=websocket.chat.local
        ports:
            - "5000:5000"
        volumes:
            - ./websocket_chat:/app/websocket_chat
        working_dir: /app/websocket_chat
        command: bash -c "npm i && npm start"

    app.chat:
        image: node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=app.chat.local
        ports:
            - "80:8080"
        volumes:
            - ./app_chat:/app/app_chat
        working_dir: /app/app_chat
        command: bash -c "npm i && npm run serve"
        links:
            - websocket.chat
