version:             '3'

services:

    server.chat:
        image: node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=websocket.chat.local
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app/server
        working_dir: /app/server
        command: bash -c "npm i && npm start"

    client.chat:
        image: node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=app.chat.local
        ports:
            - "80:8080"
        volumes:
            - ./client:/app/client
        working_dir: /app/client
        command: bash -c "npm i && npm run serve"
        links:
            - server.chat
